[package]
name = "historical_options_producer"
version = "0.1.0"
edition = "2021"

[dependencies]
dotenv = "0.15.0"
reqwest = { version = "0.11", features = ["json"] }
tokio = { version = "1", features = ["full"] }
anyhow = "1.0"
rdkafka = { version = "0.29", features = ["cmake-build"] }
